/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theme;

import dao.IBooksDAO;
import dao.ILocationDAO;
import dao.IPublicserDAO;
import dao.impl.BookDAO;
import dao.impl.LocationDAO;
import dao.impl.PublicserDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import models.Book;
import models.Location;
import models.Publicser;

/**
 *
 * @author admin
 */
public class CreateBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateBook
     */
    private DefaultTableModel dftbBook;
    //Location
    private List<Location> listLocation  = new ArrayList<>();
    private ILocationDAO locationDAO;
    private Location location;
    //Publicser 
    private List<Publicser> listPublicser  = new ArrayList<>();
    private IPublicserDAO publicserDAO;
    private Publicser publicser;
    //Book
    private List<Book> listBook  = new ArrayList<>();
    private IBooksDAO bookDAO;
    private Book books;
    public CreateBook() {
        initComponents();
        bookDAO = new BookDAO();
        preapareGUI();
        loadData();
        loadCBox();
    }
    
    private void loadCBox(){
        listLocation.removeAll(listLocation);
        listPublicser.removeAll(listPublicser);
        locationDAO = new LocationDAO();
        publicserDAO = new PublicserDAO();
        listPublicser = publicserDAO.getAll();
        listLocation = locationDAO.getAll();
        for (Location location1 : listLocation) {
            cbLocation.addItem(location1.getLocationName());
        }   
        for (Publicser publicser1 : listPublicser) {
           cbPublicser.addItem(publicser1.getPublicserName());
        }
        
        
    }

    private void preapareGUI(){
        dftbBook = new DefaultTableModel();
        dftbBook.addColumn("Mã sách");
        dftbBook.addColumn("Tên sách");
        dftbBook.addColumn("Giá sách");
        dftbBook.addColumn("Số lượng");
        dftbBook.addColumn("Năm xuất bản");
        dftbBook.addColumn("Trạng thái");
        dftbBook.addColumn("Nhà xuất bản");
        dftbBook.addColumn("Vị trí");
    }
    
    private void loadData(){
        
        listBook = bookDAO.getAll();
        Vector v;
      
        
        for (Book book : listBook) {
            v = new Vector();
            v.add(book.getBooksCode());
            v.add(book.getBooksName());
            v.add(book.getBooksPrice());
            v.add(book.getQuantity());
            v.add(book.getYear());
            if (book.getStatus() == 1) {
                v.add("Còn sách");
            }else{
                v.add("Hết sách");
            }
            v.add(book.getPublicserName());
            v.add(book.getLocationName());
            
            jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
               int pos = jTable1.getSelectedRow();
               if(pos <0){
                   pos=0;
               }
               
               books = listBook.get(pos);
               setData(book);
               
            }
        });
            
            dftbBook.addRow(v);
        }
        
//        listBook.forEach(s->System.out.println(s.toString()));
        
        jTable1.setModel(dftbBook);
    }
    
    
    private void setData(Book book){
        jtBookCode.setText(book.getBooksCode());
        jtBookName.setText(book.getBooksName());
        String price = String.valueOf(book.getBooksPrice());
        String quantity = String.valueOf(book.getQuantity());
        String year = String.valueOf(book.getYear());
        String status = String.valueOf(book.getStatus());
        jtBPrice.setText(price);
        jQuantity.setText(quantity);
        jtYear.setText(year);
        jtStatus.setText(status);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtBookCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtBookName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtBPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jQuantity = new javax.swing.JTextField();
        jtYear = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtStatus = new javax.swing.JTextField();
        cbLocation = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbPublicser = new javax.swing.JComboBox<>();
        kButton2 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnRefesh = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        btnSearch = new keeptoo.KButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setVisible(true);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(51, 153, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(300, 470));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quản lý sách");
        jLabel6.setPreferredSize(new java.awt.Dimension(215, 29));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vị trí");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mã sách");

        jtBookCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtBookCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtBookCode.setCaretColor(new java.awt.Color(204, 0, 255));
        jtBookCode.setBackground(new java.awt.Color(0,0,0,0));
        jtBookCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBookCodeActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên sách");

        jtBookName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtBookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtBookName.setCaretColor(new java.awt.Color(204, 0, 255));
        jtBookName.setBackground(new java.awt.Color(0,0,0,0));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Giá sách");

        jtBPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtBPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtBPrice.setCaretColor(new java.awt.Color(204, 0, 255));
        jtBPrice.setBackground(new java.awt.Color(0,0,0,0));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Số lượng");

        jQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jQuantity.setCaretColor(new java.awt.Color(204, 0, 255));
        jQuantity.setBackground(new java.awt.Color(0,0,0,0));

        jtYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtYear.setCaretColor(new java.awt.Color(204, 0, 255));
        jtYear.setBackground(new java.awt.Color(0,0,0,0));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Năm xuất bản");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Trạng thái");

        jtStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtStatus.setCaretColor(new java.awt.Color(204, 0, 255));
        jtStatus.setBackground(new java.awt.Color(0,0,0,0));

        cbLocation.setPreferredSize(new java.awt.Dimension(100, 25));
        cbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocationActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nhà xuất bản");

        cbPublicser.setPreferredSize(new java.awt.Dimension(100, 25));
        cbPublicser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPublicserActionPerformed(evt);
            }
        });

        kButton2.setText("Thêm");
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton2.setkFillButton(false);
        kButton2.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setPreferredSize(new java.awt.Dimension(80, 30));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("Sửa");
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton3.setkFillButton(false);
        kButton3.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton3.setPreferredSize(new java.awt.Dimension(80, 30));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPublicser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtBookName)
                    .addComponent(jtBPrice)
                    .addComponent(jQuantity)
                    .addComponent(jtYear)
                    .addComponent(jtStatus)
                    .addComponent(jtBookCode)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(cbPublicser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jtBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jtBPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addComponent(jtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(544, 35));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(20, 445));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(544, 60));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp", "A-Z", "Z-A" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(80, 30));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox3);

        btnRefesh.setText("Tải lại");
        btnRefesh.setkBorderRadius(0);
        btnRefesh.setkEndColor(new java.awt.Color(51, 153, 0));
        btnRefesh.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnRefesh.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnRefesh.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnRefesh.setkStartColor(new java.awt.Color(0, 204, 204));
        btnRefesh.setPreferredSize(new java.awt.Dimension(80, 30));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });
        jPanel5.add(btnRefesh);

        btnDelete.setText("Xóa");
        btnDelete.setkBorderRadius(0);
        btnDelete.setkEndColor(new java.awt.Color(51, 153, 0));
        btnDelete.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnDelete.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnDelete.setkStartColor(new java.awt.Color(0, 204, 204));
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete);

        btnSearch.setText("Tìm kiếm");
        btnSearch.setkBorderRadius(0);
        btnSearch.setkEndColor(new java.awt.Color(51, 153, 0));
        btnSearch.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnSearch.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnSearch.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnSearch.setkStartColor(new java.awt.Color(0, 204, 204));
        btnSearch.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearch);

        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel5.add(jTextField1);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Giá sách", "Số lượng", "Năm xuất bản", "Trạng thái", "Nhà xuất bản", "Vị trí"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(800, 64));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBookCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBookCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBookCodeActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        books = new Book(jtBookCode.getText(), title, TOP_ALIGNMENT, SOMEBITS, WIDTH, ERROR, title, title);
        bookDAO.save(books);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocationActionPerformed
        
    }//GEN-LAST:event_cbLocationActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void cbPublicserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPublicserActionPerformed

       
    }//GEN-LAST:event_cbPublicserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnRefesh;
    private keeptoo.KButton btnSearch;
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JComboBox<String> cbPublicser;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jQuantity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtBPrice;
    private javax.swing.JTextField jtBookCode;
    private javax.swing.JTextField jtBookName;
    private javax.swing.JTextField jtStatus;
    private javax.swing.JTextField jtYear;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
