/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theme;

import dao.IAuthorDAO;
import dao.IBookAuthorDAO;
import dao.IBookCategoryDAO;
import dao.ICategoryDAO;
import dao.impl.AuthorDAO;
import dao.impl.BookAuthorDAO;
import dao.impl.BookCategoryDAO;
import dao.impl.CategoryDAO;
import dao.impl.LocationDAO;
import dao.impl.PublicserDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Author;
import models.BookAuthor;
import models.BookCategory;
import models.Category;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author admin
 */
public class JLogAddDeitalBook extends javax.swing.JDialog {

    /**
     * Creates new form JLogAddDeitalBook
     */
    //Author
    private List<Author> listAuthor = new ArrayList<>();
    private IAuthorDAO authorDAO;
    private Author author;
    private DefaultTableModel dftAuthor;

    //Category
    private List<Category> listCategory = new ArrayList<>();
    private ICategoryDAO categoryDAO;
    private Category category;
    private DefaultTableModel dftCategory;

    public JLogAddDeitalBook(java.awt.Frame parent, boolean modal, int idBook, String bookName) {
        super(parent, modal);
        initComponents();
        lbBookCode.setText(String.valueOf(idBook));
        lbBookName.setText(bookName);
        loadCBox();
    }

    private void loadCBox() {

        listCategory.removeAll(listCategory);
        listAuthor.removeAll(listAuthor);

        authorDAO = new AuthorDAO();
        categoryDAO = new CategoryDAO();

        listAuthor = authorDAO.getAll();
        listCategory = categoryDAO.getAll();

        listAuthor.forEach(cbAuthor::addItem);
        listCategory.forEach(cbCategory::addItem);

        AutoCompleteDecorator.decorate(cbAuthor);
        AutoCompleteDecorator.decorate(cbCategory);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jmDelCate = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jmDelAuthor = new javax.swing.JMenuItem();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCategory = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cbAuthor = new javax.swing.JComboBox<>();
        btnAddAuthor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cbCategory = new javax.swing.JComboBox<>();
        btnAddCategory = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAuthor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbBookName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbBookCode = new javax.swing.JLabel();

        jmDelCate.setText("jMenuItem1");
        jmDelCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDelCateActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jmDelCate);

        jmDelAuthor.setText("jMenuItem2");
        jmDelAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDelAuthorActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jmDelAuthor);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Các thể loại"));

        tbCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Thể loại"
            }
        ));
        tbCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbCategoryMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbCategory);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác giả"));

        btnAddAuthor.setText("Thêm tác giả");
        btnAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAuthorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAddAuthor))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thể loại"));

        btnAddCategory.setText("Thêm thể loại");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCategory))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Các tác giả"));

        tbAuthor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên tác giả"
            }
        ));
        tbAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbAuthorMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbAuthor);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_save_16px_1.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên sách:");

        lbBookName.setText("jLabel2");

        jLabel3.setText("Mã sách:");

        lbBookCode.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBookName)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbBookCode)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbBookName)
                    .addComponent(jLabel3)
                    .addComponent(lbBookCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAuthorActionPerformed
        Author selectAuthor = (Author) cbAuthor.getSelectedItem();
        dftAuthor = (DefaultTableModel) tbAuthor.getModel();
        boolean flag = true;
        Vector dataAuthor = dftAuthor.getDataVector();
        if (dataAuthor.size() <= 0) {
            Object[] row = {selectAuthor.getAuthorId(), selectAuthor.getAuthorName()};
            dftAuthor.addRow(row);
        } else if (dataAuthor.size() > 0) {
            for (int i = 0; i < dataAuthor.size(); i++) {
                Object objAuthorId = ((Vector) dataAuthor.elementAt(i)).elementAt(0);
                Object objAuthorName = ((Vector) dataAuthor.elementAt(i)).elementAt(1);
                int dataId = (Integer) objAuthorId;
                if (selectAuthor.getAuthorId() == dataId) {
                    JOptionPane.showMessageDialog(this, "Đã có " + objAuthorName);
                    flag = false;
                }
            }
            if (flag == true) {
                Object[] row = {selectAuthor.getAuthorId(), selectAuthor.getAuthorName()};
                dftAuthor.addRow(row);
            }
        }

    }//GEN-LAST:event_btnAddAuthorActionPerformed

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        Category selectCategory = (Category) cbCategory.getSelectedItem();
        dftCategory = (DefaultTableModel) tbCategory.getModel();

        boolean flag = true;
        Vector dataCategory = dftCategory.getDataVector();
        if (dataCategory.size() <= 0) {
            Object[] row = {selectCategory.getCategoryId(), selectCategory.getCategoryName()};
            dftCategory.addRow(row);
        } else if (dataCategory.size() > 0) {
            for (int i = 0; i < dataCategory.size(); i++) {
                Object objCategoryId = ((Vector) dataCategory.elementAt(i)).elementAt(0);
                Object objCategoryName = ((Vector) dataCategory.elementAt(i)).elementAt(1);
                int dataId = (Integer) objCategoryId;
                if (selectCategory.getCategoryId() == dataId) {
                    JOptionPane.showMessageDialog(this, "Đã có " + objCategoryName);
                    flag = false;
                }
            }
            if (flag == true) {
                Object[] row = {selectCategory.getCategoryId(), selectCategory.getCategoryName()};
                dftCategory.addRow(row);
            }
        }

    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void tbAuthorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAuthorMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu3.show(tbAuthor, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbAuthorMouseReleased

    private void tbCategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoryMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu2.show(tbCategory, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbCategoryMouseReleased

    private void jmDelAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDelAuthorActionPerformed
        if (tbAuthor.getSelectedRow() != -1) {
            // remove selected row from the model
            if ((DefaultTableModel) tbAuthor.getModel() == dftAuthor) {
                dftAuthor.removeRow(tbAuthor.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Xóa thành công");
            }
        }
    }//GEN-LAST:event_jmDelAuthorActionPerformed

    private void jmDelCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDelCateActionPerformed
        if (tbCategory.getSelectedRow() != -1) {
            if ((DefaultTableModel) tbCategory.getModel() == dftCategory) {
                dftCategory.removeRow(tbCategory.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Xóa thành công");
            }
        }
    }//GEN-LAST:event_jmDelCateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//add author
        IBookAuthorDAO bookAuthorDAO = new BookAuthorDAO();
        Vector dataAuthor = dftAuthor.getDataVector();
        int idBook = Integer.valueOf(lbBookCode.getText());
        for (int i = 0; i < dataAuthor.size(); i++) {
            Object objAuthorId = ((Vector) dataAuthor.elementAt(i)).elementAt(0);
            int authorId = (Integer) objAuthorId;
            BookAuthor bookAuthor = new BookAuthor(idBook, authorId);
            bookAuthorDAO.save(bookAuthor);
        }

        //add category
        IBookCategoryDAO bookCategoryDAO = new BookCategoryDAO();
        Vector dataCate = dftCategory.getDataVector();

        for (int i = 0; i < dataCate.size(); i++) {
            Object objCategoryId = ((Vector) dataCate.elementAt(i)).elementAt(0);
            int categoryId = (Integer) objCategoryId;
            BookCategory bookCategory = new BookCategory(idBook, categoryId);
            bookCategoryDAO.save(bookCategory);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogAddDeitalBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogAddDeitalBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogAddDeitalBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogAddDeitalBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JLogAddDeitalBook dialog = new JLogAddDeitalBook(new javax.swing.JFrame(), true, 0,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAuthor;
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JComboBox<Author> cbAuthor;
    private javax.swing.JComboBox<Category> cbCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem jmDelAuthor;
    private javax.swing.JMenuItem jmDelCate;
    private javax.swing.JLabel lbBookCode;
    private javax.swing.JLabel lbBookName;
    private javax.swing.JTable tbAuthor;
    private javax.swing.JTable tbCategory;
    // End of variables declaration//GEN-END:variables
}
