/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theme;

import dao.IBillsDAO;
import dao.IBillsDetailDAO;
import dao.IBooksDAO;
import dao.IReaderDAO;
import dao.impl.BiilsDAO;
import dao.impl.BillsDetailDAO;
import dao.impl.BookDAO;
import dao.impl.ReaderDAO;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import models.Bills;
import models.BillsDetail;
import models.Book;
import models.Reader;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import utils.Myultis;

/**
 *
 * @author admin
 */
public class ManagerBiils extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManagerBiils
     */
    private List<Reader> listReader = new ArrayList<>();
    private IReaderDAO readerDAO;
    private Reader reader;

    private List<Book> listBook = new ArrayList<>();
    private IBooksDAO bookDAO;
    private Book book;

    private List<Bills> listBill = new ArrayList<>();
    private Bills bills;
    private IBillsDAO billDAO;
    private IBillsDetailDAO billsDetailDAO;
    private DefaultTableModel defaultTableModel;
    private DefaultTableModel dftbBills;

    public ManagerBiils() {
        initComponents();
        readerDAO = new ReaderDAO();
        bookDAO = new BookDAO();
        billDAO = new BiilsDAO();
        loadComboBox();
        preapareGUI();
        loadData();
    }

    private void loadComboBox() {
        listReader.removeAll(listReader);
        listBook.removeAll(listBook);
        listReader = readerDAO.getAll();
        listBook = bookDAO.getAll();
        listReader.forEach(cbReader::addItem);
        listBook.forEach(cbBook::addItem);
        AutoCompleteDecorator.decorate(cbReader);
        AutoCompleteDecorator.decorate(cbBook);
        spnQuantity.setValue(1);

    }

    private void preapareGUI() {
        dftbBills = new DefaultTableModel();
        dftbBills.addColumn("Mã phiếu");
        dftbBills.addColumn("Ngày mượn");
        dftbBills.addColumn("Ngày trả");
        dftbBills.addColumn("Tên người mượn");
        dftbBills.addColumn("Số điện thoại");
        dftbBills.addColumn("Địa chỉ");
        dftbBills.addColumn("Giới tính");
    }

    private void loadData() {
        listBill = billDAO.getAll();
        Vector v;

        for (Bills bills1 : listBill) {
            v = new Vector();
            v.add(bills1.getBillsId());
            v.add(bills1.getCreatedDate());
            v.add(bills1.getPayDay());
            v.add(bills1.getReaderName());
            v.add(bills1.getPhone());
            v.add(bills1.getAddress());
            if (bills1.getGender() == 1) {
                v.add("Nam");
            } else {
                v.add("Nữ");
            }

            dftbBills.addRow(v);
        }

//        listBook.forEach(s->System.out.println(s.toString()));
        jTable2.setModel(dftbBills);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAddBill = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAddDetailBills = new javax.swing.JButton();
        cbBook = new javax.swing.JComboBox<>();
        lbNameBook = new javax.swing.JLabel();
        lbNXB = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConfirmReader = new javax.swing.JButton();
        btnSaveBills = new javax.swing.JButton();
        lbReaderId = new javax.swing.JLabel();
        lbReaderName = new javax.swing.JLabel();
        cbReader = new javax.swing.JComboBox<>();
        dpEndDate = new org.jdesktop.swingx.JXDatePicker();
        dpStartDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        lbIdBill = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlAddBill.setPreferredSize(new java.awt.Dimension(1500, 617));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin phiếu mượn"));

        jLabel1.setText("Số điện thoại");

        jLabel2.setText("Mã người mượn");

        jLabel3.setText("Tên người mượn");

        jLabel4.setText("Ngày mượn");

        jLabel5.setText("Ngày trả");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm sách mượn"));

        jLabel15.setText("Mã sách ");

        jLabel16.setText("Tên sách");

        jLabel17.setText("Nhà xuất bản");

        btnAddDetailBills.setText("Thêm");
        btnAddDetailBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDetailBillsActionPerformed(evt);
            }
        });

        cbBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBookActionPerformed(evt);
            }
        });

        spnQuantity.setPreferredSize(new java.awt.Dimension(15, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddDetailBills, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNXB)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cbBook, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNameBook)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNameBook))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNXB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnAddDetailBills)
                .addGap(36, 36, 36))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Mã sách", "Tên sách", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnConfirmReader.setText("Xác nhận thông tin người mượn");
        btnConfirmReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmReaderActionPerformed(evt);
            }
        });

        btnSaveBills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_save_16px_1.png"))); // NOI18N
        btnSaveBills.setText("Lưu phiếu");
        btnSaveBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillsActionPerformed(evt);
            }
        });

        lbReaderId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lbReaderName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        cbReader.setForeground(new java.awt.Color(255, 255, 255));
        cbReader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbReaderMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbReaderMouseReleased(evt);
            }
        });
        cbReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReaderActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã phiếu:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbReader, 0, 215, Short.MAX_VALUE)
                                .addComponent(dpStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lbReaderId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(109, 109, 109)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbIdBill, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbReaderName)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(btnConfirmReader, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSaveBills))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbReaderName)
                                .addComponent(lbReaderId))
                            .addComponent(cbReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(lbIdBill))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmReader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveBills, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAddBillLayout = new javax.swing.GroupLayout(pnlAddBill);
        pnlAddBill.setLayout(pnlAddBillLayout);
        pnlAddBillLayout.setHorizontalGroup(
            pnlAddBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlAddBillLayout.setVerticalGroup(
            pnlAddBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm phiếu mượn", pnlAddBill);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Ngày mượn", "Ngày trả", "Tên độc giả", "Địa chỉ", "Số điện thoại", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jXSearchField1.setText("jXSearchField1");
        jXSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXSearchField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách phiếu mượn", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReaderActionPerformed
        Reader selectReader = (Reader) cbReader.getSelectedItem();
        String readerId = String.valueOf(selectReader.getReaderId());
        lbReaderId.setText(readerId);
        lbReaderName.setText(selectReader.getReaderName());
//        System.out.println("" + selectReader.getReaderName());
    }//GEN-LAST:event_cbReaderActionPerformed

    private void cbReaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbReaderMouseClicked

    }//GEN-LAST:event_cbReaderMouseClicked

    private void cbReaderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbReaderMouseReleased

    }//GEN-LAST:event_cbReaderMouseReleased

    private void btnConfirmReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmReaderActionPerformed
        billDAO = new BiilsDAO();
        LocalDate startDate = Myultis.convertDatetoLocalDate(dpStartDate.getDate());
        LocalDate endDate = Myultis.convertDatetoLocalDate(dpEndDate.getDate());
        int readerId = Integer.valueOf(lbReaderId.getText());
        bills = new Bills(readerId, startDate, endDate);
        int newId = billDAO.save(bills);
        bills = billDAO.findOne(newId);
        String bId = String.valueOf(bills.getBillsId());
        lbIdBill.setText(bId);

    }//GEN-LAST:event_btnConfirmReaderActionPerformed

    private void cbBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBookActionPerformed
        Book selectBook = (Book) cbBook.getSelectedItem();
        String bookName = selectBook.getBooksName();
        String bookNXB = selectBook.getPublicserName();
        lbNameBook.setText(bookName);
        lbNXB.setText(bookNXB);
    }//GEN-LAST:event_cbBookActionPerformed

    private void btnAddDetailBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDetailBillsActionPerformed
        Book selectBook = (Book) cbBook.getSelectedItem();
        int quantity = (int) spnQuantity.getValue();
        Object[] row = {selectBook.getBookId(), selectBook.getBooksCode(), selectBook.getBooksName(), quantity};
        defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(row);

    }//GEN-LAST:event_btnAddDetailBillsActionPerformed

    private void btnSaveBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillsActionPerformed
        billsDetailDAO = new BillsDetailDAO();
        Vector data = defaultTableModel.getDataVector();
        int billId = Integer.valueOf(lbIdBill.getText());
        for (int i = 0; i < data.size(); i++) {
            Object objBookId = ((Vector) data.elementAt(i)).elementAt(0);
            Object objQuantity = ((Vector) data.elementAt(i)).elementAt(3);
            int bookId = (int) objBookId;
            int quantity = (int) objQuantity;
            BillsDetail billsDetail = new BillsDetail(billId, bookId, quantity);
            billsDetailDAO.save(billsDetail);
        }

    }//GEN-LAST:event_btnSaveBillsActionPerformed

    private void jXSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXSearchField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDetailBills;
    private javax.swing.JButton btnConfirmReader;
    private javax.swing.JButton btnSaveBills;
    private javax.swing.JComboBox<Book> cbBook;
    private javax.swing.JComboBox<Reader> cbReader;
    private org.jdesktop.swingx.JXDatePicker dpEndDate;
    private org.jdesktop.swingx.JXDatePicker dpStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private javax.swing.JLabel lbIdBill;
    private javax.swing.JLabel lbNXB;
    private javax.swing.JLabel lbNameBook;
    private javax.swing.JLabel lbReaderId;
    private javax.swing.JLabel lbReaderName;
    private javax.swing.JPanel pnlAddBill;
    private javax.swing.JSpinner spnQuantity;
    // End of variables declaration//GEN-END:variables

}
